[package]
name = "mgit"
version = "0.1.0"
authors = ["Sarp Basaraner <sarpbasaraner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
rust-ini = "0.15"
flate2 = "1.0"